version: '3.9'

services:
  api1:
    image: rinhav2
    depends_on:
      postgres: 
        condition: service_healthy
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"

  api2:
    image: rinhav2
    depends_on:
      postgres: 
        condition: service_healthy
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"

  postgres:
    image: postgres:alpine     
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d postgres'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "300MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

networks:
  app-network: